# Generated by Django 6.0.3 on 2026-04-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment',
        ),
    ]
