# Generated by Django 6.0.3 on 2026-04-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0003_rename_content_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nigger',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='nigger.comments', verbose_name='Комментарий'),
        ),
    ]
