# Generated by Django 6.0.3 on 2026-04-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0005_remove_nigger_comment_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='time_create',
        ),
    ]
