# Generated by Django 6.0.3 on 2026-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0006_remove_comments_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='nigger',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='com', to='nigger.comments', verbose_name='Комментарий'),
        ),
    ]
