# Generated by Django 6.0.3 on 2026-04-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0007_nigger_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
