# Generated by Django 6.0.3 on 2026-04-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0008_remove_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nigger',
            old_name='comment',
            new_name='comments',
        ),
    ]
