# Generated by Django 6.0.3 on 2026-04-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nigger', '0009_rename_comment_nigger_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nigger',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='nigger.nigger'),
        ),
    ]
